### ISSUE TITLE
Maybe just use an existing platform?

### ISSUE THREAD

**Issue by olety** [TibetanAppTeam/tibetan-learning#1]
You can make an anki/memrise/... deck instead, it'd be easier. Or do you plan to monetize it in the future?

**Comment by olety** [comment]
Anyway, here's some useful links if you're planning to start your own site:

- https://en.wikipedia.org/wiki/Spaced_repetition
- http://bit.ly/InterleavingVsBlocking
- http://bit.ly/PrinciplesOfLanguageLearning
- http://bit.ly/PhonologicalLoop

In other words,
- use SRS for everything
- use weird mnemonics that are easy to remember for vocab (at least in the beginning)
- add a native speaker's audio when you teach a word (Pata can do it for sentences, or if it's too much work you could also try https://forvo.com/ for individual words - it has an API)
- add a pronunciation guide (use IPA if there isn't one developed specifically for Tibetan; according to [this](https://en.wikipedia.org/wiki/Standard_Tibetan) Tibetan has two tones so mark the high/low syllables)
- either add extensive grammar explanation in English or try to teach it from context using sentences
- try to eliminate all non-tibetan explanations as soon as possible and just teach words through other words (ie you can teach "antonym" as "cheap/expensive, large/small, ...", then teach "synonym" as "an antonym of the word 'antonym'", and then use them to explain similar concepts, etc.

**Comment by PaulinaBinas** [comment]
I tried using existing platforms, and while it works pretty well for languages with latin alphabet, I found it very tough to make any significant progress with Tibetan. Also, I've checked out any existing mobile and web apps for learning Tibetan and they are so poor it made me really sad. That's why we decided to make something on our own - to practice and gain some experience but also to make some valuable contribution to this language and its learners.

I already thought of making Pata the first reader of our audio, but we also need to decide if we will present different dialects. He has central Tibetan dialect, but he can't really understand the western and eastern ones. So it could be useful to allow the choice between those.

Also, we need to decide on technology first, before planning anything more specific. I'm planning on using Java for the server-side as I'd really like to hone my skills, and for the front we will probably use the newest Angular.

Anyway, I'll go over your suggestions :) And in case of any more ideas or questions feel free to write here.

**Comment by olety** [comment]
Tbh I've only used them for Japanese and Korean (a bit), so they better be good for romance/germanic languages then 😋Since I was able to get JLPT N4 certification with like 3.5 months of self study.

I don't know how having different characters would hinder basic principles of spaced repetition though, especially since Tibetan doesn't use hieroglyphs like Japanese/Chinese. But it's great that you're trying to make it easier for everyone to learn 😊 

Also, try asking for feature requests on reddit.com/r/languagelearning or reddit.com/r/tibetanlanguage (this page is kinda dead though), you'll certainly get some ideas that you could implement in the app + see how much demand is there for this product.

Some Anki vocab decks that you can "borrow" contents from ([they're basically sqlite DBs](http://decks.wikia.com/wiki/Anki_APKG_format_documentation)):

https://ankiweb.net/shared/info/3465980039
https://ankiweb.net/shared/info/1916342611
https://ankiweb.net/shared/info/2111472183

PS: I hope you didn’t mean stuff like duolingo, memrise etc. 😋they’re (mostly) bad for studying anything and not just non-Roman languages.

**Comment by olety** [comment]
Well, it seems like you don't contribute to the project anymore so I'll close this. ¯\\\_(ツ)_/¯
